### PR TITLE
Fixed memory issue discovered when fuzzing

### LINKED ISSUE #4: raw_message fuzzing crashes
The following crashes were found with the fuzzer

## Crash 1 - RegisterResponse::from_apdu
https://github.com/Devolutions/slauth/blob/master/src/u2f/proto/raw_message.rs#L130

Panics if the allocated buffer is smaller than `ASN1_MAX_FOLLOWING_LEN_BYTES + 2`.

```rust
let mut attestation_cert = vec![0u8; data_len - cursor.position() as usize];
cursor.read_exact(&mut attestation_cert[..])?;

let cert_len = attestation_cert_length(&attestation_cert[0..ASN1_MAX_FOLLOWING_LEN_BYTES + 2])?;
```

## Crash 2 - RegisterResponse::from_apdu split_off
https://github.com/Devolutions/slauth/blob/master/src/u2f/proto/raw_message.rs#L149

Panics if `cert_len` is larger than attestation_cert.len()

```rust
let cert_len = attestation_cert_length(&attestation_cert[0..ASN1_MAX_FOLLOWING_LEN_BYTES + 2])?;
let signature = attestation_cert.split_off(cert_len);
```

## Crash 3 - Response::read_from
https://github.com/Devolutions/slauth/blob/master/src/u2f/proto/raw_message.rs#L598

Panics if `slice_len` is smaller than 2  (negative index).

```rust
let slice_len = slice.len();
let rsp_data = &slice[0..slice_len - 2];
```

## Crash 4 - integer overflow in attestation_cert_length()

https://github.com/Devolutions/slauth/blob/master/src/u2f/proto/raw_message.rs#L674

The value of `len` can overflow. I suggest we limit the number of bytes we attempt to read.

```rust
let following_bytes = len & ASN1_DEFINITE_LONG_FOLLOWING_MASK;
let mut len: usize = 0;
for i in 0..following_bytes {
    len = len * 256 + (asn1[(2 + i) as usize] as usize);
}
```

### PR DESCRIPTION
**Pull request by richerarc**
Resolve #4

### CODE REVIEW

File: src/u2f/proto/raw_message.rs [hunk 1]
```diff
@@ -649,9 +654,16 @@ pub fn attestation_cert_length(asn1: &[u8]) -> Result<usize, Error> {
         return Err(Error::AsnFormatError("Invalid ans len, expected definite long".to_string()));
     }
 
+    if following_bytes as usize + 2 >= asn1.len() {
+        return Err(Error::AsnFormatError("Invalid ans len, too many following len bytes expected".to_string()));
```
Comment (ekse) [inline src/u2f/proto/raw_message.rs]: 'ans', typo?

File: src/u2f/proto/raw_message.rs [hunk 2]
```diff
@@ -649,9 +654,16 @@ pub fn attestation_cert_length(asn1: &[u8]) -> Result<usize, Error> {
...
+    }
+
     let mut len: usize = 0;
-    for i in 0..following_bytes {
-        len = len * 256 + (asn1[(2 + i) as usize] as usize);
+    for i in 0..following_bytes as usize {
+        len = len * 256 + (asn1[2 + i] as usize);
+        if len > U2F_MAX_ATT_CERT_SIZE {
+            return Err(Error::Other("Attestation certificate don't meet len requirements".to_string()))
```
Comment (ekse) [inline src/u2f/proto/raw_message.rs]: nit: "doesn't meet"
